baseURL = "https://fefercode.github.io"
title = "FeferCode"
themesDir = "../.."
theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 24

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  avatar = "images/avatar.jpg"
  author = "Jakub Majewski"
  description = "Hi, I'm iOS developer and this blog is my way to become Full Stack Developer"
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/FeferCode"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jakub-majewski-ios/"

  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

    # Red theme
 #  [params.style]
 #    darkestColor = "#d35050"
 #    darkestColor = "#D34B4B"   
 #    darkColor = "#212121"
 #    lightColor = "#d6d6d6"
 #    lightestColor = "#d3d3d3"
 #    primaryColor = "#bbbbbb"

  #Custom theme
   [params.style]
     darkestColor = "#D34B4B"   
     darkColor = "#212121"
     lightColor = "#d6d6d6"
     lightestColor = "#d3d3d3"
     primaryColor = "#bbbbbb"